### ISSUE TITLE
A question about depth and xyz

### ISSUE THREAD

**Issue by yuyunlong2002** [xiaoaoran/FPS-Net#4]
Hello, I want to ask why we should use depth and xyz at the same time. I observed in your code that the depth is calculated using xyz（depth=np.linalg.norm(self.points, 2, axis=1)）, so there is a correlation between the two. Why do we use depth when using xyz , is there any result indicating that using depth and xyz simultaneously will have better effect?

**Comment by xiaoaoran** [comment]
Hi @yuyunlong2002 

Yes, although depth can be directly calculated from xyz, adding this modality can still enrich input since the network does not implicitly learn depth information. This is the trick also used by existing works such as SqueezeSegV2 and rangenet++.

You can find relevant discussion and analysis in Table 4 of our paper [FPS-Net](https://arxiv.org/pdf/2103.00738.pdf).

**Comment by xiaoaoran** [comment]
@yuyunlong2002 

Hi, I closed this issue since there are no further questions. Please feel free to re-open it if you have any other questions.
